### ISSUE TITLE
Click on the link does not add to calendar

### ISSUE THREAD

**Issue by mathbouq** [zachfeldman/card_to_calendar#1]
I updated the extension, which required some more permissions (which I granted).
Now, the "card to calendar" button is permanently visible and active, even on pages that do not contain any flight information, and even when all tabs containing flight information are closed.
On Gmail, in the flight information card, the "add to calendar" link displays only after I click the "card to calendar" button. I don't know whether this is a technical limitation, but it would be more convenient if the link displayed directly, without any additional action, in my opinion.

The problem occurs when I click on the "add to calendar" link: this action opens a new calendar tab, but no event is added to the calendar (although the flight information seems to be included in the URL).
I tried with 3 different flights of 2 different airlines, which gave me the same result.
I can provide the URLs, if necessary.
My version of Chrome is up to date (36.0.1985.143 m).
I am logged in on several gmail accounts at once, and I tried the extension on data which is in the first account (id=0 in the gmail URL).

**Comment by zachfeldman** [comment]
Hey @mbouquet , thanks so much for your feedback. Yes, this is a technical limitation. I can probably namespace the button to only Gmail pages but probably not to just pages with flight information...that would be difficult based off of my testing.

Providing the URLs would be really helpful in debugging the issues!

I appreciate everyone's patience as we try to make this thing work...(it works for me =))

**Comment by mathbouq** [comment]
Here are 4 URLs that do not create an event in my calendar:
https://www.google.com/calendar/render?action=TEMPLATE&dates=20140818T092500+/20140818T113500+&text=Vueling+Flight+6251&details=Confirmation+%23A7LRGJ%0AFrom:+Rome+FCO%0ATo:+Paris+ORY%0AConfirmation+%23:+Confirmation+%23A7LRGJ&sf=true&output=xml

https://www.google.com/calendar/render?action=TEMPLATE&dates=20140715T151000+/20140715T170500+&text=Air+France+Flight+1649&details=Confirmation+%238EL2A5%0AFrom:+Barcelone+BCN%0ATo:+Paris+CDG%0AConfirmation+%23:+Confirmation+%238EL2A5&sf=true&output=xml

https://www.google.com/calendar/render?action=TEMPLATE&dates=20140703T152500+/20140703T170500+&text=Air+France+Flight+1948&details=Confirmation+%238EL2A5%0AFrom:+Paris+CDG%0ATo:+Barcelone+BCN%0AConfirmation+%23:+Confirmation+%238EL2A5&sf=true&output=xml

https://www.google.com/calendar/render?action=TEMPLATE&dates=20140731T121500+/20140731T141000+&text=Transavia+Airlines+Flight+3322&details=Confirmation+%23IEEWQE%0AFrom:+Paris+ORY%0ATo:+Pise+PSA%0AConfirmation+%23:+Confirmation+%23IEEWQE&sf=true&output=xml

**Comment by zachfeldman** [comment]
Hey @mbouquet , thanks for that - can you try it now? I just updated it to version 3.0.0. Working on the namespacing issue.

**Comment by mathbouq** [comment]
This update fixed the issue: everything works fine for me, now. Thanks!
I have some suggestions for improvement that I will post later on a new thread.

**Comment by zachfeldman** [comment]
@mbouquet awesome! Glad it worked out. Would love to hear your suggestions, we'll see what's possible.
