### ISSUE TITLE
Dates and Timezones not correct (no easy fix)

### ISSUE THREAD

**Issue by jmiserez** [zachfeldman/card_to_calendar#5]
There are two issues regarding the handling of times and dates:

1) If the flight arrives the next day in the morning (e.g. leaves 9PM, arrives 6AM next day) then the date for the arrival is wrong: It will put both departure and arrival as the same date, which is obviously impossible.
2) If the times are in the local timezones of the respective airports then the times will be wrong. Example:  Leave time is 8PM timezone Paris, arrival time is 10PM timezone New York, the flight takes 12 hours. Then it will put the flight as only 2h long, as it doesn't know about the timezone.

From looking at the Gmail card HTML, there seems to be no easy way to fix this: The date/timezone is not specified in the HTML card at all. So basically this is just an FYI so you are aware of these shortcomings/pitfalls with the Gmail cards. Also this means that implementing issue #3 is probably not a good idea at least for flights.

**Comment by zachfeldman** [comment]
Hey @jmiserez thanks for the FYI! I'm going to close this issue but if you plan to work on the repo, feel free to open a new one for issue number 1 and a pull request.
